
	<div class="col-xs-10">
			<div class="page-title"><h1> Terms & Conditions </h1></div>
			<div class="panel-lg panel panel-default">
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-12">
							<p>By using or reading any pages on&nbsp; <a href="#">www.mcdelivery.co.id </a> dan <a href="#">www.mcdonalds.co.id&nbsp;</a>&nbsp;(collectively, "Sites"), you agree to the terms and conditions contained therein, namely, the Web Order Terms and Conditions, Website Terms and Privacy Policy (collectively, "Terms &amp; Conditions"). If you do not agree, you should not use the Sites.</p>
							<h2>WEB ORDER TERMS AND CONDITIONS</h2>
							<ul>
								<li>Minimum order amount is Rp. 21.500,- (not including delivery charge )</li>
								<li>Delivery charge is Rp. 13.000,- (tax included) per order</li>
								<li>Specials orders requests on chicken parts cannot be done in website ordering.</li>
								<li>Special orders on burger and other menus (no pickle, extra lettuce, no ketchup, etc) are allowed by filling the "Order Remark" column in the last page before payment.</li>
								<li>In order for us to maintain high standards of quality and hygiene, there are periods of equipment maintenance during which certain food items will not be available. For quality reasons, we do not deliver ice cream cone and McCafe products.</li>
								<li>Lunch/Dinner/Supper orders are taken until 04.45am.</li>
								<li>Prices of meals may vary with your choice of drink. The price of your meal will be reflected on your order form prior to confirmation.</li>
								
								 <table class="table-tnc"><tbody><tr><td colspan="2">Menu</td><td>Chili Sauce</td><td>Ketchup</td><td>BBQ / Sweet&amp;Sour Sauce</td></tr><tr><td colspan="2">A la carte / Paket Hemat (non-breakfast)</td><td style="text-align:center">1</td><td></td><td></td></tr><tr><td colspan="2">Panas 1</td><td style="text-align:center">1</td><td></td><td></td></tr><tr><td colspan="2">Panas 2 (Nasi / fries)</td><td style="text-align:center">2</td><td></td><td></td></tr><tr><td colspan="2">Panas Spesial</td><td style="text-align:center">1</td><td></td><td></td></tr><tr><td colspan="2">Happy Meal</td><td></td><td style="text-align:center">1</td><td></td></tr><tr><td rowspan="2">McNuggets</td><td>4pcs / 6pcs</td><td></td><td></td><td style="text-align:center">1</td></tr><tr><td>9pcs</td><td></td><td></td><td style="text-align:center">2</td></tr><tr><td>French Fries</td><td>(Reg. / Med. / Lrg.)</td><td style="text-align:center">1</td><td></td><td></td></tr><tr><td colspan="2">Lainnya</td><td colspan="3" style="text-align:center">(dengan permintaan)</td></tr></tbody></table>
								 <li>Every Happy Meal™ comes with a pre-assigned toy, and subject to stock availability in the restaurant.</li>
								 <li>Maximum Rp.500.000,- of orders on&nbsp;<a href="#">www.mcdelivery.co.id</a>. For amounts above that, please call the McDelivery hotline at 14045.</li>
								 <li>We currently do not accept payments using debit card.</li>
								 <li>For orders via online, only cash payment will be accepted.</li>
								 <li>Although we will try our best to deliver your food orders within the indicated timeframe, to help ensure the safety of our McDeliver™ riders, delivery times may be affected due to bad weather and/or traffic conditions.</li>
								 <li>Although we will try our best to deliver your food orders within the indicated timeframe, to help ensure the safety of our McDeliver™ riders, delivery times may be affected due to bad weather and/or traffic conditions.</li>
								<li>McDeliver™ service is subject to availability. We reserve the right to reject any order.</li>
								 <li>Access to the McDelivery™ Site or hotline may be suspended temporarily and without notice in the case of system failure, maintenance or repair or for reasons beyond our McDonald's reasonable control. McDonalds disclaims all liability for any malfunction, suspension or interruption of the Site or hotline, including inaccessibility due to network problems.</li>
								 <li>The Web Order Terms, and any disputes arising from the Web Order Terms, shall be governed by Indonesia law. You agree to submit to the exclusive jurisdiction of the courts of Indonesia regarding any such dispute. A person who is not a party to these Web Order Terms shall have no right under the Contract (Rights of Third Parties) Act to enforce any part of these Web Order Terms.</li>
								 <li>The Web Order Terms, and any disputes arising from the Web Order Terms, shall be governed by Indonesia law. You agree to submit to the exclusive jurisdiction of the courts of Indonesia regarding any such dispute. A person who is not a party to these Web Order Terms shall have no right under the Contract (Rights of Third Parties) Act to enforce any part of these Web Order Terms.</li>
							</ul>
							<h2>WEBSITE TERMS</h2>
							<h3>RESTRICTIONS ON USE</h3>
							<p>Material from&nbsp;<a href="#" target="_blank">http://www.mcdonalds.co.id</a>,&nbsp;<a href="#">www.mcdelivery.co.id</a>&nbsp;and any other World Wide Web site owned, operated, licensed, or controlled by McDonald's Corporation or any of its related, affiliated, or subsidiary companies (together, "McDonald's") may not be copied or distributed, or republished, uploaded, posted, or transmitted in any way, without the prior written consent of McDonald's EXCEPT: you may download one copy of the material on one computer for your personal, non-commercial and home use only, provided you do not delete or change any copyright, trademark, or other proprietary notices. Modification or use of any materials on the Site for any other purpose may violate McDonald's intellectual property rights. The material on this Site is provided for lawful purposes only. If you download software from our site, the software, including all files, images, contained in or generated by the software, and accompanying data (together, the "Software") are deemed to be licensed to you by McDonald's. No rights and interests in any such material or intellectual property rights shall be transferred to you, but shall remain with McDonald's. You may not resell, decompile, reverse engineer, disassemble, or otherwise convert the Software to a human perceivable form, except to the extent permitted by law.</p>
							<h3>RESTRICTION OF LIABILITY</h3>
							<p>McDonald's will not be liable for any costs, damages or injury caused by, including but not limited to, any failure of performance, error, omission, interruption, defect, delay in operation of transmission, computer virus, or line failure. McDonald's will not be liable for any damages or injury, including but not limited to, special or consequential damages that result from the use of, or the inability to use, the materials in this site, even if there is negligence or where McDonald's (or an authorized McDonald representative) has been advised of the possibility of such damages, or both. The above limitation or exclusion may not apply to you to the extent that applicable law may not allow the limitation or exclusion of liability for incidental or consequential damages. McDonald's total liability to you for all losses (including loss of profits or loss of opportunity), damages, and causes of action (in contract, tort (including without limitation, negligence), or otherwise) will not be greater than the amount you paid to access this site (if any).</p>
							<h3>SUBMISSIONS</h3>
							<p>All remarks, suggestions, ideas, graphics, or other information communicated to McDonald's through this site (together, the "Submission") will forever be the property of McDonald's. McDonald's will not be required to treat any Submission as confidential, and will not be liable for any ideas for its business (including without limitation, product, or advertising ideas) and will not incur any liability as a result of any similarities that may appear in future McDonald's operations. Without limitation, McDonald's will have exclusive ownership of all present and future existing rights to the Submission of every kind and nature everywhere. Except as noted below in this paragraph, McDonald's will be entitled to use the Submission for any commercial or other purpose whatsoever without compensation to you or any other person sending the Submission. Personally identifiable information that may be received at this site is provided voluntarily by a visitor to this site. This information is for internal purposes only and is not sold or otherwise transferred to third parties of McDonald's or to other entities who are not involved in the operation of this site. Therefore, the above right to use Submissions is subject to this limited use of this information and excludes non-retained information. You acknowledge that you are responsible for whatever material you submit, and you, not McDonald's shall have full responsibility for the message, including its legality, reliability, appropriateness, originality, and all relevant intellectual property rights residing therein.</p>
							<h3>JURISDICTION</h3>
							<p>Except as described otherwise, all materials on the Site are made available only to provide information about McDonald's. McDonald's controls and operates this Site from its headquarters in Oak Brook Illinois, United States of America and makes no representation that these materials are appropriate or available for use in other locations. If you use this site from other locations you are responsible for compliance with applicable local laws. Some software from this site may be subject to export control laws applicable (including the United States and Indonesia) and the software may not be downloaded or otherwise exported or reexported except in accordance with all applicable laws. : (a) into (or to a national or resident of) any country to which the U.S. has placed an embargo, including without limitation, Cuba, Iran, Iraq, Libya, North Korea, Syria, or Yugoslavia; (b) to everyone on the US Treasury Department's Specially Designated Nationals list, or (c) the US Commerce Department's Table of Denial Orders. If you download or use the Software, you represent and warrant that you are not located in, or under the control of, or a national or any such country or on any such list.</p>
							<h3>DISCLAIMER</h3>
							<p>The material in this site could include technical inaccuracies or typographical errors. McDonald's may make changes or improvements at any time. THE MATERIALS IN THIS SITE ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESSED OR IMPLIED, TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW. McDonald's DISCLAIMS ALL WARRANTIES AND CONDITIONS OF SATISFACTORY QUALITY, MERCHANTABILITY AND OF FITNESS FOR A PARTICULAR PURPOSE. McDonald's DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE MATERIAL WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. McDonald's DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF OR THE RESULT OF THE USE OF THE MATERIAL IN THIS SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT McDonald's) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. THE ABOVE EXCLUSION MAY NOT APPLY TO YOU, TO THE EXTENT THAT APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR CONDITIONS.</p>
							<h3>TERMINATION</h3>
							<p>McDonald's or you may terminate this agreement at any time. Upon termination of the agreement by you, you are required to destroy: (a) all materials obtained from all McDonald's sites, (b) all related documentation and all copies and installations (together, the "Materials"); and (c) you shall cease all access and use of the Site. McDonald's may terminate this agreement immediately without notice if, in its sole judgment, you breach any term or condition of this agreement. Upon termination, you must destroy all materials.</p>
							<h3>MISCELLANEOUS</h3>
							<p>These Website Terms will be governed and be interpreted pursuant to the laws of Indonesia, notwithstanding any principles of conflicts of law. You agree to submit to the exclusive jurisdiction of the courts of Indonesia regarding any such dispute. A person who is not a party to these Terms shall have no right under the Contract (Rights of Third Parties) Act to enforce any part of these Terms. If any part of these Website Terms are unlawful, void, or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of any remaining provisions. Possible evidence of use of this site for illegal purposes will be provided to law enforcement authorities. This is the entire agreement between the parties relating to the use of this Site. McDonald's can revise these Terms and Conditions at any time by updating this posting. McDonald's products and services are available in many parts of the world. However, the McDonald's Site may describe products and services that are not available worldwide. This Site may be linked to other sites which are not maintained by McDonald's. McDonald's is not responsible for the content of those sites. The inclusion of any link to such sites does not imply endorsement by McDonald's of the sites. These Website Terms, together with the Privacy Policy and any other policies which you may consent to, constitute the entire agreement between McDonald’s and you with respect to your use of the Site.</p>
							<h2>TRADEMARK INFORMATION</h2>
							<p>Without prejudice to any other intellectual property rights which McDonald's Corporation and/or its affiliates may own, the following trademarks used herein are owned by the McDonald's Corporation and/or its affiliates:  1-800-MC1-STCK, Always Quality. Always Fun., America's Favorite Fries, Arch Deluxe, Aroma Café, Automac, Big Mac, Big N' Tasty, Big Xtra!, Birdie, the Early Bird and Design, Black History Makers of tomorrow, Bolshoi Mac, Boston Market, Cajita Feliz, Changing The Face of The World, Chicken McGrill, Chicken McNuggets, Chicken Selects, Chipolte Mexican Grill, Cuarto De Libra, Did Somebody Say , Donatos Pizza, emac digital, Egg McMuffin, Extra Value Meal, Filet-O-Fish, French Fry Box Design, Fruit Buzz, Gep Op Mac, Golden Arches, Golden Arches Logo, Good Jobs For Good People, Good Times. Great Taste., Gospelfest, Great Breaks, Grimace and Design, Groenteburger, HACER, Hamburglar and Design, Hamburger University, Happy Meal, Happy Meal Box Design, Have You Had Your Break Today?, Healthy Growing Up, Helping Hands Logo, Hey, i'm lovin' it, It Could Happen!, "it's what i eat and what i do", Iam Hungry and Design, Immunize for Healthy Lives, Kiwiburger, Lifting Kids To A Better Tomorrow, Mac Attack, Mac Jr., Mac Tonight and Design, McDonald's Racing Team Design, Made For You, McBaby, McBacon, McBurger, McBus, McCafe, McChicken, McDia Feliz, MCDirect Shares, McDonaldland, McDonald's , McDonald's All American High School Basketball Game, McDonald's All American High School Jazz Bank, McDonald's All Star Racing Team, McDonald's Building Design, McDonald's Earth Effort, McDonald's Earth Effort Logo, McDonald's Express, McDonald's Express Logo, McDonald's Is Your Kind of Place, McDonald's Means Opportunity, McDouble, McDrive, McExpress, McFamily, McFlurry, McFranchise, McGriddles, McGrilled Chicken, McHappy Day, McHero, McJobs, McKids, McKids Logo, McKroket, McMaco, McMemories, McMenu, McMusic, McNifica, McNuggets, McNuggets Kip, McOz, McPlane, McPollo, McPrep, McRecycle USA, McRib, McRoyal, McScholar, McScholar of the Year, McSwing, McWorld, Mighty Kids Meal, Mighty Wings, Millennium Dreamers, Morning Mac, Quarter Pounder, RMCC, RMHC, Ronald McDonald and Design, Ronald McDonald House, Ronald McDonald House Charities, Ronald McDonald House Charities Logo, Ronald McDonald House Logo, Ronald Scholars, Sausage McGriddles, Sausage McMuffin, Single Arch Logo, Speedee Logo, Super Size, Teriyaki McBurger, The House That Love Built, The House That Love Built Design, twoallbeefpattiesspecialsaucelettucecheesepicklesoniononasesameseedbun, Vegi Mac, We Love to See You Smile, What's On Your Place, When the U.S. Wins You Win, World Children's Day, World Children's Day Logo, World Famous Fries, You Deserve a Break Today, McDWireless.</p>
							<p>All other trademarks are the property of the respective trademark owners.</p>
						</div>
						
					</div>
				</div>
			</div>
			
	</div>
</div>
</div>
</body>
</html>